on:
  push:
    branches:
      - develop/package-down-and-rhub-workflows
  pull_request:
    branches:
      - develop/package-down-and-rhub-workflows
permissions:
  contents: write
  pull-requests: write
name: pkgdown.yaml
jobs:
  pkgdown:
    name: Pkgdown site
    uses: NovoNordisk-OpenSource/r.workflows/.github/workflows/pkgdown.yaml@main
    with:
      use_local_setup_action: true