# runs r cmd check + unit tests in inst/tinytest
on:
  pull_request:
    branches: [main, dev]

name: r-cmd-check

jobs:
  r-cmd-check:
    runs-on: ${{ matrix.config.os }}

    name: ${{ matrix.config.os }} (${{ matrix.config.r }})

    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: ubuntu-latest,   r: 'release'}

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_KEEP_PKG_SOURCE: yes

    steps:
      - uses: actions/checkout@v4
      - uses: r-lib/actions/setup-pandoc@v2
      - uses: r-lib/actions/setup-tinytex@v2
      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.config.r }}
          http-user-agent: ${{ matrix.config.http-user-agent }}
          use-public-rspm: true

      - name: Install libpoppler-cpp-dev # required to install pdftools (R pkg)
        run: sudo apt-get install libpoppler-cpp-dev

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: |
            any::lintr
            any::devtools
            any::rcmdcheck
          needs: check, lint

      - uses: r-lib/actions/check-r-package@v2
        with:
          upload-snapshots: true
          args: 'c("--ignore-vignettes")'
          build_args: 'c("--no-build-vignettes")'

      # test examples that have not been tested with r cmd check because of
      # \donttest
      - name: check examples
        run: make check-examples

      # test that committed man pages and namespace are up-to-date
      - name: build roxygen documentation
        run: |
          cp -r man .man
          cp -r NAMESPACE .NAMESPACE
          make roxygen

      - name: Check man pages
        run: diff -r man .man

      - name: Check NAMESPACE
        run: diff -r NAMESPACE .NAMESPACE

      - name: Lint package
        run: lintr::lint_package()
        shell: Rscript {0}
        env:
          LINTR_ERROR_ON_LINT: true
